Splitter class sprint 1
briancatraguna/Simple-Classifier pull request #7
Opened 2023-05-05 23:10 UTC by dgh007786

This is a simple working code for split by percentage, random state, shuffle, and stratify.

2023-05-05 23:57 UTC, briancatraguna requested changes
Overall looks great man, great job. Just added some minor comments.

Also as a group, I think we need to decide on the docstring convention. There are different docstring conventions we can choose, each has different formatting and wordings:
<img width="731" alt="Screen Shot 2023-05-05 at 19 54 31" src="https://user-images.githubusercontent.com/32363208/236586283-9923a4cc-6357-491b-81b6-706e3a4615e6.png">

We need to keep it consistent through out the whole codebase so that when it is generated by sphinx it'll be easier to follow and read as its consistent. 

I'm not sure if sphinx also has their own docstring convention. @Alan052918 can you help confirm?

2023-05-05 23:57 UTC, briancatraguna commented on simple_classifier/Splitter/Splitter.py
> +        X is the feature matrix. It is typincally two dimentional array or matrix of shape (n_samples,n_features)
typo `typically`

2023-05-05 23:57 UTC, briancatraguna commented on simple_classifier/Splitter/Splitter_subclasses.py
> +@Splitter.register("Percentage_split")
Let's keep codenames all in lower case for consistency -> `percentage_split`. What do you think?

2023-05-05 23:57 UTC, briancatraguna commented on simple_classifier/Splitter/Splitter_subclasses.py
> +@Splitter.register("Percentage_split_w_shuffle")
`percentage_split_w_shuffle`

2023-05-05 23:57 UTC, briancatraguna commented on simple_classifier/Splitter/Splitter_subclasses.py
> +@Splitter.register("Percentage_split_w_stratify")
`percentage_split_w_stratify`

2023-05-07 01:36 UTC, jayeshgaur approved these changes

2023-05-08 22:02 UTC, Alan052918 commented
Sphinx docstring format: https://sphinx-rtd-tutorial.readthedocs.io/en/latest/docstrings.html

2023-05-09 03:06 UTC, Alan052918 requested changes
- Need another splitter (or a parameter to all splitters in this file) that take a list of indices as seed from the user and further split the rest of the data based on this seed.
- Nitpick: Could extract each `Splitter` subclass into its own file. Idiomatically python file names are all lowercases delimited by underscores, but since Brian named files in PascalCase in the skeleton we can stick to it. But you could rename this file as `SplitterSubclasses` to keep consistency.

2023-05-09 03:12 UTC, briancatraguna approved these changes

2023-05-09 17:55 UTC, Alan052918 approved these changes

2023-05-09 20:13 UTC, merged